### ISSUE TITLE
Opposite direction? 

### ISSUE THREAD

**Issue by davidrenne** [fsamin/go-wsqueue#1]
I really want to use this library for a message queue needed for websocket but my problem is that I need my clients to publish data to a topic and I need my server to subscribe and listen to the queue for messages.  Our server cannot make a websocket network connection to the clients since they are behind the firewall and don't have connectable ips to host a socket to connect to.

Do you have any ideas here?

**Comment by fsamin** [comment]
Hello,
In the websocket protocol, the websocket is opened by the HTTP client, not the server.
When the websocket is opened both client and server can write data in the websocket. But this lib doesn't implement the pattern you are looking for.

I think you should consider Kafka as a message broker for your usecase
